apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prow-exporter
  namespace: prow
rules:
  - apiGroups:
      - prow.k8s.io
    resources:
      - prowjobs
    verbs:
      - get
      - list
      - watch
