apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prow-exporter
  namespace: prow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prow-exporter
subjects:
  - kind: ServiceAccount
    name: prow-exporter
