apiVersion: v1
kind: Service
metadata:
  name: prow-exporter
  namespace: prow
spec:
  ports:
    - name: metrics
      port: 9855
      protocol: TCP
      targetPort: 9855
  selector:
    app.kubernetes.io/name: prow-exporter
