# SPDX-FileCopyrightText: 2023 Christoph Mewes
# SPDX-License-Identifier: MIT

builds:
  - env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.BuildTag={{.Version}} -X main.BuildCommit={{.Commit}} -X main.BuildDate={{.Date}}'
    goos:
      - darwin
      - freebsd
      - linux
    goarch:
      - amd64
      - '386'
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: freebsd
        goarch: '386'
    binary: '{{ .ProjectName }}'
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    image_templates:
      - ghcr.io/xrstf/{{ .ProjectName }}:{{ .Version }}-amd64
    build_flag_templates:
      - "--platform=linux/amd64"
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    image_templates:
      - ghcr.io/xrstf/{{ .ProjectName }}:{{ .Version }}-arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: ghcr.io/xrstf/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/xrstf/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/xrstf/{{ .ProjectName }}:{{ .Version }}-arm64
archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: true
    strip_parent_binary_folder: true
checksum:
  disable: true
