# SPDX-FileCopyrightText: 2023 Christoph Mewes
# SPDX-License-Identifier: MIT

version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    network_mode: host
    volumes:
      - "./prometheus/config:/etc/prometheus:ro"
      - "./prometheus/data:/prometheus"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --storage.tsdb.retention.time=999d

  grafana:
    image: grafana/grafana:latest
    network_mode: host
    volumes:
      - "./grafana/data:/var/lib/grafana"
      - "./grafana/logs:/var/log/grafana"
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
